---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - typescript
      - javascript
    exclude_fingerprints:
  tslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.ts"
exclude_paths:
- test/**
- docs/**