verbose: false
instrumentation:
    compact: false
    preserve-comments: true
    excludes: ["dist/**", "test/**", "**/*.d.ts", "**/*.spec.ts"]
    include-all-sources: true
reporting:
    print: both
    watermarks:
        statements: [95, 97]
        lines: [95, 97]
        functions: [95, 97]
        branches: [95, 97]
check:
    global:
        branches: 95
        functions: 95
        lines: 95
        statements: 95
    each:
        branches: 80
        functions: 80
        lines: 80
        statements: 80